// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fakes

import (
	context "context"
	sync "sync"

	controller "github.com/rancher/norman/controller"
	objectclient "github.com/rancher/norman/objectclient"
	v3 "github.com/rancher/types/apis/cluster.cattle.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

var (
	lockHarborTagListerMockGet  sync.RWMutex
	lockHarborTagListerMockList sync.RWMutex
)

// Ensure, that HarborTagListerMock does implement HarborTagLister.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborTagLister = &HarborTagListerMock{}

// HarborTagListerMock is a mock implementation of HarborTagLister.
//
//     func TestSomethingThatUsesHarborTagLister(t *testing.T) {
//
//         // make and configure a mocked HarborTagLister
//         mockedHarborTagLister := &HarborTagListerMock{
//             GetFunc: func(namespace string, name string) (*v3.HarborTag, error) {
// 	               panic("mock out the Get method")
//             },
//             ListFunc: func(namespace string, selector labels.Selector) ([]*v3.HarborTag, error) {
// 	               panic("mock out the List method")
//             },
//         }
//
//         // use mockedHarborTagLister in code that requires HarborTagLister
//         // and then make assertions.
//
//     }
type HarborTagListerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespace string, name string) (*v3.HarborTag, error)

	// ListFunc mocks the List method.
	ListFunc func(namespace string, selector labels.Selector) ([]*v3.HarborTag, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Selector is the selector argument value.
			Selector labels.Selector
		}
	}
}

// Get calls GetFunc.
func (mock *HarborTagListerMock) Get(namespace string, name string) (*v3.HarborTag, error) {
	if mock.GetFunc == nil {
		panic("HarborTagListerMock.GetFunc: method is nil but HarborTagLister.Get was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockHarborTagListerMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockHarborTagListerMockGet.Unlock()
	return mock.GetFunc(namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedHarborTagLister.GetCalls())
func (mock *HarborTagListerMock) GetCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockHarborTagListerMockGet.RLock()
	calls = mock.calls.Get
	lockHarborTagListerMockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *HarborTagListerMock) List(namespace string, selector labels.Selector) ([]*v3.HarborTag, error) {
	if mock.ListFunc == nil {
		panic("HarborTagListerMock.ListFunc: method is nil but HarborTagLister.List was just called")
	}
	callInfo := struct {
		Namespace string
		Selector  labels.Selector
	}{
		Namespace: namespace,
		Selector:  selector,
	}
	lockHarborTagListerMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockHarborTagListerMockList.Unlock()
	return mock.ListFunc(namespace, selector)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedHarborTagLister.ListCalls())
func (mock *HarborTagListerMock) ListCalls() []struct {
	Namespace string
	Selector  labels.Selector
} {
	var calls []struct {
		Namespace string
		Selector  labels.Selector
	}
	lockHarborTagListerMockList.RLock()
	calls = mock.calls.List
	lockHarborTagListerMockList.RUnlock()
	return calls
}

var (
	lockHarborTagControllerMockAddClusterScopedFeatureHandler sync.RWMutex
	lockHarborTagControllerMockAddClusterScopedHandler        sync.RWMutex
	lockHarborTagControllerMockAddFeatureHandler              sync.RWMutex
	lockHarborTagControllerMockAddHandler                     sync.RWMutex
	lockHarborTagControllerMockEnqueue                        sync.RWMutex
	lockHarborTagControllerMockGeneric                        sync.RWMutex
	lockHarborTagControllerMockInformer                       sync.RWMutex
	lockHarborTagControllerMockLister                         sync.RWMutex
	lockHarborTagControllerMockStart                          sync.RWMutex
	lockHarborTagControllerMockSync                           sync.RWMutex
)

// Ensure, that HarborTagControllerMock does implement HarborTagController.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborTagController = &HarborTagControllerMock{}

// HarborTagControllerMock is a mock implementation of HarborTagController.
//
//     func TestSomethingThatUsesHarborTagController(t *testing.T) {
//
//         // make and configure a mocked HarborTagController
//         mockedHarborTagController := &HarborTagControllerMock{
//             AddClusterScopedFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedFeatureHandler method")
//             },
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, handler v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddFeatureHandler method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, handler v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             EnqueueFunc: func(namespace string, name string)  {
// 	               panic("mock out the Enqueue method")
//             },
//             GenericFunc: func() controller.GenericController {
// 	               panic("mock out the Generic method")
//             },
//             InformerFunc: func() cache.SharedIndexInformer {
// 	               panic("mock out the Informer method")
//             },
//             ListerFunc: func() v3.HarborTagLister {
// 	               panic("mock out the Lister method")
//             },
//             StartFunc: func(ctx context.Context, threadiness int) error {
// 	               panic("mock out the Start method")
//             },
//             SyncFunc: func(ctx context.Context) error {
// 	               panic("mock out the Sync method")
//             },
//         }
//
//         // use mockedHarborTagController in code that requires HarborTagController
//         // and then make assertions.
//
//     }
type HarborTagControllerMock struct {
	// AddClusterScopedFeatureHandlerFunc mocks the AddClusterScopedFeatureHandler method.
	AddClusterScopedFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborTagHandlerFunc)

	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, handler v3.HarborTagHandlerFunc)

	// AddFeatureHandlerFunc mocks the AddFeatureHandler method.
	AddFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, handler v3.HarborTagHandlerFunc)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(namespace string, name string)

	// GenericFunc mocks the Generic method.
	GenericFunc func() controller.GenericController

	// InformerFunc mocks the Informer method.
	InformerFunc func() cache.SharedIndexInformer

	// ListerFunc mocks the Lister method.
	ListerFunc func() v3.HarborTagLister

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, threadiness int) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedFeatureHandler holds details about calls to the AddClusterScopedFeatureHandler method.
		AddClusterScopedFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler v3.HarborTagHandlerFunc
		}
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler v3.HarborTagHandlerFunc
		}
		// AddFeatureHandler holds details about calls to the AddFeatureHandler method.
		AddFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborTagHandlerFunc
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Handler is the handler argument value.
			Handler v3.HarborTagHandlerFunc
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Generic holds details about calls to the Generic method.
		Generic []struct {
		}
		// Informer holds details about calls to the Informer method.
		Informer []struct {
		}
		// Lister holds details about calls to the Lister method.
		Lister []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threadiness is the threadiness argument value.
			Threadiness int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AddClusterScopedFeatureHandler calls AddClusterScopedFeatureHandlerFunc.
func (mock *HarborTagControllerMock) AddClusterScopedFeatureHandler(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborTagHandlerFunc) {
	if mock.AddClusterScopedFeatureHandlerFunc == nil {
		panic("HarborTagControllerMock.AddClusterScopedFeatureHandlerFunc: method is nil but HarborTagController.AddClusterScopedFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Handler     v3.HarborTagHandlerFunc
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockHarborTagControllerMockAddClusterScopedFeatureHandler.Lock()
	mock.calls.AddClusterScopedFeatureHandler = append(mock.calls.AddClusterScopedFeatureHandler, callInfo)
	lockHarborTagControllerMockAddClusterScopedFeatureHandler.Unlock()
	mock.AddClusterScopedFeatureHandlerFunc(ctx, enabled, name, clusterName, handler)
}

// AddClusterScopedFeatureHandlerCalls gets all the calls that were made to AddClusterScopedFeatureHandler.
// Check the length with:
//     len(mockedHarborTagController.AddClusterScopedFeatureHandlerCalls())
func (mock *HarborTagControllerMock) AddClusterScopedFeatureHandlerCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Handler     v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Handler     v3.HarborTagHandlerFunc
	}
	lockHarborTagControllerMockAddClusterScopedFeatureHandler.RLock()
	calls = mock.calls.AddClusterScopedFeatureHandler
	lockHarborTagControllerMockAddClusterScopedFeatureHandler.RUnlock()
	return calls
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *HarborTagControllerMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, handler v3.HarborTagHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("HarborTagControllerMock.AddClusterScopedHandlerFunc: method is nil but HarborTagController.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v3.HarborTagHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockHarborTagControllerMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockHarborTagControllerMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, handler)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedHarborTagController.AddClusterScopedHandlerCalls())
func (mock *HarborTagControllerMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Handler     v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v3.HarborTagHandlerFunc
	}
	lockHarborTagControllerMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockHarborTagControllerMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddFeatureHandler calls AddFeatureHandlerFunc.
func (mock *HarborTagControllerMock) AddFeatureHandler(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc) {
	if mock.AddFeatureHandlerFunc == nil {
		panic("HarborTagControllerMock.AddFeatureHandlerFunc: method is nil but HarborTagController.AddFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborTagHandlerFunc
	}{
		Ctx:     ctx,
		Enabled: enabled,
		Name:    name,
		Sync:    sync,
	}
	lockHarborTagControllerMockAddFeatureHandler.Lock()
	mock.calls.AddFeatureHandler = append(mock.calls.AddFeatureHandler, callInfo)
	lockHarborTagControllerMockAddFeatureHandler.Unlock()
	mock.AddFeatureHandlerFunc(ctx, enabled, name, sync)
}

// AddFeatureHandlerCalls gets all the calls that were made to AddFeatureHandler.
// Check the length with:
//     len(mockedHarborTagController.AddFeatureHandlerCalls())
func (mock *HarborTagControllerMock) AddFeatureHandlerCalls() []struct {
	Ctx     context.Context
	Enabled func() bool
	Name    string
	Sync    v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborTagHandlerFunc
	}
	lockHarborTagControllerMockAddFeatureHandler.RLock()
	calls = mock.calls.AddFeatureHandler
	lockHarborTagControllerMockAddFeatureHandler.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *HarborTagControllerMock) AddHandler(ctx context.Context, name string, handler v3.HarborTagHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("HarborTagControllerMock.AddHandlerFunc: method is nil but HarborTagController.AddHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Handler v3.HarborTagHandlerFunc
	}{
		Ctx:     ctx,
		Name:    name,
		Handler: handler,
	}
	lockHarborTagControllerMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockHarborTagControllerMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, handler)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedHarborTagController.AddHandlerCalls())
func (mock *HarborTagControllerMock) AddHandlerCalls() []struct {
	Ctx     context.Context
	Name    string
	Handler v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Handler v3.HarborTagHandlerFunc
	}
	lockHarborTagControllerMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockHarborTagControllerMockAddHandler.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *HarborTagControllerMock) Enqueue(namespace string, name string) {
	if mock.EnqueueFunc == nil {
		panic("HarborTagControllerMock.EnqueueFunc: method is nil but HarborTagController.Enqueue was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockHarborTagControllerMockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	lockHarborTagControllerMockEnqueue.Unlock()
	mock.EnqueueFunc(namespace, name)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//     len(mockedHarborTagController.EnqueueCalls())
func (mock *HarborTagControllerMock) EnqueueCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockHarborTagControllerMockEnqueue.RLock()
	calls = mock.calls.Enqueue
	lockHarborTagControllerMockEnqueue.RUnlock()
	return calls
}

// Generic calls GenericFunc.
func (mock *HarborTagControllerMock) Generic() controller.GenericController {
	if mock.GenericFunc == nil {
		panic("HarborTagControllerMock.GenericFunc: method is nil but HarborTagController.Generic was just called")
	}
	callInfo := struct {
	}{}
	lockHarborTagControllerMockGeneric.Lock()
	mock.calls.Generic = append(mock.calls.Generic, callInfo)
	lockHarborTagControllerMockGeneric.Unlock()
	return mock.GenericFunc()
}

// GenericCalls gets all the calls that were made to Generic.
// Check the length with:
//     len(mockedHarborTagController.GenericCalls())
func (mock *HarborTagControllerMock) GenericCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborTagControllerMockGeneric.RLock()
	calls = mock.calls.Generic
	lockHarborTagControllerMockGeneric.RUnlock()
	return calls
}

// Informer calls InformerFunc.
func (mock *HarborTagControllerMock) Informer() cache.SharedIndexInformer {
	if mock.InformerFunc == nil {
		panic("HarborTagControllerMock.InformerFunc: method is nil but HarborTagController.Informer was just called")
	}
	callInfo := struct {
	}{}
	lockHarborTagControllerMockInformer.Lock()
	mock.calls.Informer = append(mock.calls.Informer, callInfo)
	lockHarborTagControllerMockInformer.Unlock()
	return mock.InformerFunc()
}

// InformerCalls gets all the calls that were made to Informer.
// Check the length with:
//     len(mockedHarborTagController.InformerCalls())
func (mock *HarborTagControllerMock) InformerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborTagControllerMockInformer.RLock()
	calls = mock.calls.Informer
	lockHarborTagControllerMockInformer.RUnlock()
	return calls
}

// Lister calls ListerFunc.
func (mock *HarborTagControllerMock) Lister() v3.HarborTagLister {
	if mock.ListerFunc == nil {
		panic("HarborTagControllerMock.ListerFunc: method is nil but HarborTagController.Lister was just called")
	}
	callInfo := struct {
	}{}
	lockHarborTagControllerMockLister.Lock()
	mock.calls.Lister = append(mock.calls.Lister, callInfo)
	lockHarborTagControllerMockLister.Unlock()
	return mock.ListerFunc()
}

// ListerCalls gets all the calls that were made to Lister.
// Check the length with:
//     len(mockedHarborTagController.ListerCalls())
func (mock *HarborTagControllerMock) ListerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborTagControllerMockLister.RLock()
	calls = mock.calls.Lister
	lockHarborTagControllerMockLister.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *HarborTagControllerMock) Start(ctx context.Context, threadiness int) error {
	if mock.StartFunc == nil {
		panic("HarborTagControllerMock.StartFunc: method is nil but HarborTagController.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Threadiness int
	}{
		Ctx:         ctx,
		Threadiness: threadiness,
	}
	lockHarborTagControllerMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockHarborTagControllerMockStart.Unlock()
	return mock.StartFunc(ctx, threadiness)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedHarborTagController.StartCalls())
func (mock *HarborTagControllerMock) StartCalls() []struct {
	Ctx         context.Context
	Threadiness int
} {
	var calls []struct {
		Ctx         context.Context
		Threadiness int
	}
	lockHarborTagControllerMockStart.RLock()
	calls = mock.calls.Start
	lockHarborTagControllerMockStart.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *HarborTagControllerMock) Sync(ctx context.Context) error {
	if mock.SyncFunc == nil {
		panic("HarborTagControllerMock.SyncFunc: method is nil but HarborTagController.Sync was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockHarborTagControllerMockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	lockHarborTagControllerMockSync.Unlock()
	return mock.SyncFunc(ctx)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//     len(mockedHarborTagController.SyncCalls())
func (mock *HarborTagControllerMock) SyncCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockHarborTagControllerMockSync.RLock()
	calls = mock.calls.Sync
	lockHarborTagControllerMockSync.RUnlock()
	return calls
}

var (
	lockHarborTagInterfaceMockAddClusterScopedFeatureHandler   sync.RWMutex
	lockHarborTagInterfaceMockAddClusterScopedFeatureLifecycle sync.RWMutex
	lockHarborTagInterfaceMockAddClusterScopedHandler          sync.RWMutex
	lockHarborTagInterfaceMockAddClusterScopedLifecycle        sync.RWMutex
	lockHarborTagInterfaceMockAddFeatureHandler                sync.RWMutex
	lockHarborTagInterfaceMockAddFeatureLifecycle              sync.RWMutex
	lockHarborTagInterfaceMockAddHandler                       sync.RWMutex
	lockHarborTagInterfaceMockAddLifecycle                     sync.RWMutex
	lockHarborTagInterfaceMockController                       sync.RWMutex
	lockHarborTagInterfaceMockCreate                           sync.RWMutex
	lockHarborTagInterfaceMockDelete                           sync.RWMutex
	lockHarborTagInterfaceMockDeleteCollection                 sync.RWMutex
	lockHarborTagInterfaceMockDeleteNamespaced                 sync.RWMutex
	lockHarborTagInterfaceMockGet                              sync.RWMutex
	lockHarborTagInterfaceMockGetNamespaced                    sync.RWMutex
	lockHarborTagInterfaceMockList                             sync.RWMutex
	lockHarborTagInterfaceMockObjectClient                     sync.RWMutex
	lockHarborTagInterfaceMockUpdate                           sync.RWMutex
	lockHarborTagInterfaceMockWatch                            sync.RWMutex
)

// Ensure, that HarborTagInterfaceMock does implement HarborTagInterface.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborTagInterface = &HarborTagInterfaceMock{}

// HarborTagInterfaceMock is a mock implementation of HarborTagInterface.
//
//     func TestSomethingThatUsesHarborTagInterface(t *testing.T) {
//
//         // make and configure a mocked HarborTagInterface
//         mockedHarborTagInterface := &HarborTagInterfaceMock{
//             AddClusterScopedFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedFeatureHandler method")
//             },
//             AddClusterScopedFeatureLifecycleFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborTagLifecycle)  {
// 	               panic("mock out the AddClusterScopedFeatureLifecycle method")
//             },
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, sync v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddClusterScopedLifecycleFunc: func(ctx context.Context, name string, clusterName string, lifecycle v3.HarborTagLifecycle)  {
// 	               panic("mock out the AddClusterScopedLifecycle method")
//             },
//             AddFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddFeatureHandler method")
//             },
//             AddFeatureLifecycleFunc: func(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborTagLifecycle)  {
// 	               panic("mock out the AddFeatureLifecycle method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, sync v3.HarborTagHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             AddLifecycleFunc: func(ctx context.Context, name string, lifecycle v3.HarborTagLifecycle)  {
// 	               panic("mock out the AddLifecycle method")
//             },
//             ControllerFunc: func() v3.HarborTagController {
// 	               panic("mock out the Controller method")
//             },
//             CreateFunc: func(in1 *v3.HarborTag) (*v3.HarborTag, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the Delete method")
//             },
//             DeleteCollectionFunc: func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
// 	               panic("mock out the DeleteCollection method")
//             },
//             DeleteNamespacedFunc: func(namespace string, name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the DeleteNamespaced method")
//             },
//             GetFunc: func(name string, opts v1.GetOptions) (*v3.HarborTag, error) {
// 	               panic("mock out the Get method")
//             },
//             GetNamespacedFunc: func(namespace string, name string, opts v1.GetOptions) (*v3.HarborTag, error) {
// 	               panic("mock out the GetNamespaced method")
//             },
//             ListFunc: func(opts v1.ListOptions) (*v3.HarborTagList, error) {
// 	               panic("mock out the List method")
//             },
//             ObjectClientFunc: func() *objectclient.ObjectClient {
// 	               panic("mock out the ObjectClient method")
//             },
//             UpdateFunc: func(in1 *v3.HarborTag) (*v3.HarborTag, error) {
// 	               panic("mock out the Update method")
//             },
//             WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
// 	               panic("mock out the Watch method")
//             },
//         }
//
//         // use mockedHarborTagInterface in code that requires HarborTagInterface
//         // and then make assertions.
//
//     }
type HarborTagInterfaceMock struct {
	// AddClusterScopedFeatureHandlerFunc mocks the AddClusterScopedFeatureHandler method.
	AddClusterScopedFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborTagHandlerFunc)

	// AddClusterScopedFeatureLifecycleFunc mocks the AddClusterScopedFeatureLifecycle method.
	AddClusterScopedFeatureLifecycleFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborTagLifecycle)

	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, sync v3.HarborTagHandlerFunc)

	// AddClusterScopedLifecycleFunc mocks the AddClusterScopedLifecycle method.
	AddClusterScopedLifecycleFunc func(ctx context.Context, name string, clusterName string, lifecycle v3.HarborTagLifecycle)

	// AddFeatureHandlerFunc mocks the AddFeatureHandler method.
	AddFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc)

	// AddFeatureLifecycleFunc mocks the AddFeatureLifecycle method.
	AddFeatureLifecycleFunc func(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborTagLifecycle)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, sync v3.HarborTagHandlerFunc)

	// AddLifecycleFunc mocks the AddLifecycle method.
	AddLifecycleFunc func(ctx context.Context, name string, lifecycle v3.HarborTagLifecycle)

	// ControllerFunc mocks the Controller method.
	ControllerFunc func() v3.HarborTagController

	// CreateFunc mocks the Create method.
	CreateFunc func(in1 *v3.HarborTag) (*v3.HarborTag, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(name string, options *v1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error

	// DeleteNamespacedFunc mocks the DeleteNamespaced method.
	DeleteNamespacedFunc func(namespace string, name string, options *v1.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(name string, opts v1.GetOptions) (*v3.HarborTag, error)

	// GetNamespacedFunc mocks the GetNamespaced method.
	GetNamespacedFunc func(namespace string, name string, opts v1.GetOptions) (*v3.HarborTag, error)

	// ListFunc mocks the List method.
	ListFunc func(opts v1.ListOptions) (*v3.HarborTagList, error)

	// ObjectClientFunc mocks the ObjectClient method.
	ObjectClientFunc func() *objectclient.ObjectClient

	// UpdateFunc mocks the Update method.
	UpdateFunc func(in1 *v3.HarborTag) (*v3.HarborTag, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(opts v1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedFeatureHandler holds details about calls to the AddClusterScopedFeatureHandler method.
		AddClusterScopedFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync v3.HarborTagHandlerFunc
		}
		// AddClusterScopedFeatureLifecycle holds details about calls to the AddClusterScopedFeatureLifecycle method.
		AddClusterScopedFeatureLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborTagLifecycle
		}
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync v3.HarborTagHandlerFunc
		}
		// AddClusterScopedLifecycle holds details about calls to the AddClusterScopedLifecycle method.
		AddClusterScopedLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborTagLifecycle
		}
		// AddFeatureHandler holds details about calls to the AddFeatureHandler method.
		AddFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborTagHandlerFunc
		}
		// AddFeatureLifecycle holds details about calls to the AddFeatureLifecycle method.
		AddFeatureLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborTagLifecycle
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborTagHandlerFunc
		}
		// AddLifecycle holds details about calls to the AddLifecycle method.
		AddLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborTagLifecycle
		}
		// Controller holds details about calls to the Controller method.
		Controller []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// In1 is the in1 argument value.
			In1 *v3.HarborTag
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// DeleteOpts is the deleteOpts argument value.
			DeleteOpts *v1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts v1.ListOptions
		}
		// DeleteNamespaced holds details about calls to the DeleteNamespaced method.
		DeleteNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// GetNamespaced holds details about calls to the GetNamespaced method.
		GetNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
		// ObjectClient holds details about calls to the ObjectClient method.
		ObjectClient []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// In1 is the in1 argument value.
			In1 *v3.HarborTag
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
	}
}

// AddClusterScopedFeatureHandler calls AddClusterScopedFeatureHandlerFunc.
func (mock *HarborTagInterfaceMock) AddClusterScopedFeatureHandler(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborTagHandlerFunc) {
	if mock.AddClusterScopedFeatureHandlerFunc == nil {
		panic("HarborTagInterfaceMock.AddClusterScopedFeatureHandlerFunc: method is nil but HarborTagInterface.AddClusterScopedFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Sync        v3.HarborTagHandlerFunc
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockHarborTagInterfaceMockAddClusterScopedFeatureHandler.Lock()
	mock.calls.AddClusterScopedFeatureHandler = append(mock.calls.AddClusterScopedFeatureHandler, callInfo)
	lockHarborTagInterfaceMockAddClusterScopedFeatureHandler.Unlock()
	mock.AddClusterScopedFeatureHandlerFunc(ctx, enabled, name, clusterName, sync)
}

// AddClusterScopedFeatureHandlerCalls gets all the calls that were made to AddClusterScopedFeatureHandler.
// Check the length with:
//     len(mockedHarborTagInterface.AddClusterScopedFeatureHandlerCalls())
func (mock *HarborTagInterfaceMock) AddClusterScopedFeatureHandlerCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Sync        v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Sync        v3.HarborTagHandlerFunc
	}
	lockHarborTagInterfaceMockAddClusterScopedFeatureHandler.RLock()
	calls = mock.calls.AddClusterScopedFeatureHandler
	lockHarborTagInterfaceMockAddClusterScopedFeatureHandler.RUnlock()
	return calls
}

// AddClusterScopedFeatureLifecycle calls AddClusterScopedFeatureLifecycleFunc.
func (mock *HarborTagInterfaceMock) AddClusterScopedFeatureLifecycle(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborTagLifecycle) {
	if mock.AddClusterScopedFeatureLifecycleFunc == nil {
		panic("HarborTagInterfaceMock.AddClusterScopedFeatureLifecycleFunc: method is nil but HarborTagInterface.AddClusterScopedFeatureLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Lifecycle   v3.HarborTagLifecycle
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockHarborTagInterfaceMockAddClusterScopedFeatureLifecycle.Lock()
	mock.calls.AddClusterScopedFeatureLifecycle = append(mock.calls.AddClusterScopedFeatureLifecycle, callInfo)
	lockHarborTagInterfaceMockAddClusterScopedFeatureLifecycle.Unlock()
	mock.AddClusterScopedFeatureLifecycleFunc(ctx, enabled, name, clusterName, lifecycle)
}

// AddClusterScopedFeatureLifecycleCalls gets all the calls that were made to AddClusterScopedFeatureLifecycle.
// Check the length with:
//     len(mockedHarborTagInterface.AddClusterScopedFeatureLifecycleCalls())
func (mock *HarborTagInterfaceMock) AddClusterScopedFeatureLifecycleCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Lifecycle   v3.HarborTagLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Lifecycle   v3.HarborTagLifecycle
	}
	lockHarborTagInterfaceMockAddClusterScopedFeatureLifecycle.RLock()
	calls = mock.calls.AddClusterScopedFeatureLifecycle
	lockHarborTagInterfaceMockAddClusterScopedFeatureLifecycle.RUnlock()
	return calls
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *HarborTagInterfaceMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, sync v3.HarborTagHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("HarborTagInterfaceMock.AddClusterScopedHandlerFunc: method is nil but HarborTagInterface.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v3.HarborTagHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockHarborTagInterfaceMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockHarborTagInterfaceMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, sync)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedHarborTagInterface.AddClusterScopedHandlerCalls())
func (mock *HarborTagInterfaceMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Sync        v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v3.HarborTagHandlerFunc
	}
	lockHarborTagInterfaceMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockHarborTagInterfaceMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddClusterScopedLifecycle calls AddClusterScopedLifecycleFunc.
func (mock *HarborTagInterfaceMock) AddClusterScopedLifecycle(ctx context.Context, name string, clusterName string, lifecycle v3.HarborTagLifecycle) {
	if mock.AddClusterScopedLifecycleFunc == nil {
		panic("HarborTagInterfaceMock.AddClusterScopedLifecycleFunc: method is nil but HarborTagInterface.AddClusterScopedLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v3.HarborTagLifecycle
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockHarborTagInterfaceMockAddClusterScopedLifecycle.Lock()
	mock.calls.AddClusterScopedLifecycle = append(mock.calls.AddClusterScopedLifecycle, callInfo)
	lockHarborTagInterfaceMockAddClusterScopedLifecycle.Unlock()
	mock.AddClusterScopedLifecycleFunc(ctx, name, clusterName, lifecycle)
}

// AddClusterScopedLifecycleCalls gets all the calls that were made to AddClusterScopedLifecycle.
// Check the length with:
//     len(mockedHarborTagInterface.AddClusterScopedLifecycleCalls())
func (mock *HarborTagInterfaceMock) AddClusterScopedLifecycleCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Lifecycle   v3.HarborTagLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v3.HarborTagLifecycle
	}
	lockHarborTagInterfaceMockAddClusterScopedLifecycle.RLock()
	calls = mock.calls.AddClusterScopedLifecycle
	lockHarborTagInterfaceMockAddClusterScopedLifecycle.RUnlock()
	return calls
}

// AddFeatureHandler calls AddFeatureHandlerFunc.
func (mock *HarborTagInterfaceMock) AddFeatureHandler(ctx context.Context, enabled func() bool, name string, sync v3.HarborTagHandlerFunc) {
	if mock.AddFeatureHandlerFunc == nil {
		panic("HarborTagInterfaceMock.AddFeatureHandlerFunc: method is nil but HarborTagInterface.AddFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborTagHandlerFunc
	}{
		Ctx:     ctx,
		Enabled: enabled,
		Name:    name,
		Sync:    sync,
	}
	lockHarborTagInterfaceMockAddFeatureHandler.Lock()
	mock.calls.AddFeatureHandler = append(mock.calls.AddFeatureHandler, callInfo)
	lockHarborTagInterfaceMockAddFeatureHandler.Unlock()
	mock.AddFeatureHandlerFunc(ctx, enabled, name, sync)
}

// AddFeatureHandlerCalls gets all the calls that were made to AddFeatureHandler.
// Check the length with:
//     len(mockedHarborTagInterface.AddFeatureHandlerCalls())
func (mock *HarborTagInterfaceMock) AddFeatureHandlerCalls() []struct {
	Ctx     context.Context
	Enabled func() bool
	Name    string
	Sync    v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborTagHandlerFunc
	}
	lockHarborTagInterfaceMockAddFeatureHandler.RLock()
	calls = mock.calls.AddFeatureHandler
	lockHarborTagInterfaceMockAddFeatureHandler.RUnlock()
	return calls
}

// AddFeatureLifecycle calls AddFeatureLifecycleFunc.
func (mock *HarborTagInterfaceMock) AddFeatureLifecycle(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborTagLifecycle) {
	if mock.AddFeatureLifecycleFunc == nil {
		panic("HarborTagInterfaceMock.AddFeatureLifecycleFunc: method is nil but HarborTagInterface.AddFeatureLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Enabled   func() bool
		Name      string
		Lifecycle v3.HarborTagLifecycle
	}{
		Ctx:       ctx,
		Enabled:   enabled,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockHarborTagInterfaceMockAddFeatureLifecycle.Lock()
	mock.calls.AddFeatureLifecycle = append(mock.calls.AddFeatureLifecycle, callInfo)
	lockHarborTagInterfaceMockAddFeatureLifecycle.Unlock()
	mock.AddFeatureLifecycleFunc(ctx, enabled, name, lifecycle)
}

// AddFeatureLifecycleCalls gets all the calls that were made to AddFeatureLifecycle.
// Check the length with:
//     len(mockedHarborTagInterface.AddFeatureLifecycleCalls())
func (mock *HarborTagInterfaceMock) AddFeatureLifecycleCalls() []struct {
	Ctx       context.Context
	Enabled   func() bool
	Name      string
	Lifecycle v3.HarborTagLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Enabled   func() bool
		Name      string
		Lifecycle v3.HarborTagLifecycle
	}
	lockHarborTagInterfaceMockAddFeatureLifecycle.RLock()
	calls = mock.calls.AddFeatureLifecycle
	lockHarborTagInterfaceMockAddFeatureLifecycle.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *HarborTagInterfaceMock) AddHandler(ctx context.Context, name string, sync v3.HarborTagHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("HarborTagInterfaceMock.AddHandlerFunc: method is nil but HarborTagInterface.AddHandler was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Sync v3.HarborTagHandlerFunc
	}{
		Ctx:  ctx,
		Name: name,
		Sync: sync,
	}
	lockHarborTagInterfaceMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockHarborTagInterfaceMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, sync)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedHarborTagInterface.AddHandlerCalls())
func (mock *HarborTagInterfaceMock) AddHandlerCalls() []struct {
	Ctx  context.Context
	Name string
	Sync v3.HarborTagHandlerFunc
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Sync v3.HarborTagHandlerFunc
	}
	lockHarborTagInterfaceMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockHarborTagInterfaceMockAddHandler.RUnlock()
	return calls
}

// AddLifecycle calls AddLifecycleFunc.
func (mock *HarborTagInterfaceMock) AddLifecycle(ctx context.Context, name string, lifecycle v3.HarborTagLifecycle) {
	if mock.AddLifecycleFunc == nil {
		panic("HarborTagInterfaceMock.AddLifecycleFunc: method is nil but HarborTagInterface.AddLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Lifecycle v3.HarborTagLifecycle
	}{
		Ctx:       ctx,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockHarborTagInterfaceMockAddLifecycle.Lock()
	mock.calls.AddLifecycle = append(mock.calls.AddLifecycle, callInfo)
	lockHarborTagInterfaceMockAddLifecycle.Unlock()
	mock.AddLifecycleFunc(ctx, name, lifecycle)
}

// AddLifecycleCalls gets all the calls that were made to AddLifecycle.
// Check the length with:
//     len(mockedHarborTagInterface.AddLifecycleCalls())
func (mock *HarborTagInterfaceMock) AddLifecycleCalls() []struct {
	Ctx       context.Context
	Name      string
	Lifecycle v3.HarborTagLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Lifecycle v3.HarborTagLifecycle
	}
	lockHarborTagInterfaceMockAddLifecycle.RLock()
	calls = mock.calls.AddLifecycle
	lockHarborTagInterfaceMockAddLifecycle.RUnlock()
	return calls
}

// Controller calls ControllerFunc.
func (mock *HarborTagInterfaceMock) Controller() v3.HarborTagController {
	if mock.ControllerFunc == nil {
		panic("HarborTagInterfaceMock.ControllerFunc: method is nil but HarborTagInterface.Controller was just called")
	}
	callInfo := struct {
	}{}
	lockHarborTagInterfaceMockController.Lock()
	mock.calls.Controller = append(mock.calls.Controller, callInfo)
	lockHarborTagInterfaceMockController.Unlock()
	return mock.ControllerFunc()
}

// ControllerCalls gets all the calls that were made to Controller.
// Check the length with:
//     len(mockedHarborTagInterface.ControllerCalls())
func (mock *HarborTagInterfaceMock) ControllerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborTagInterfaceMockController.RLock()
	calls = mock.calls.Controller
	lockHarborTagInterfaceMockController.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *HarborTagInterfaceMock) Create(in1 *v3.HarborTag) (*v3.HarborTag, error) {
	if mock.CreateFunc == nil {
		panic("HarborTagInterfaceMock.CreateFunc: method is nil but HarborTagInterface.Create was just called")
	}
	callInfo := struct {
		In1 *v3.HarborTag
	}{
		In1: in1,
	}
	lockHarborTagInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockHarborTagInterfaceMockCreate.Unlock()
	return mock.CreateFunc(in1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedHarborTagInterface.CreateCalls())
func (mock *HarborTagInterfaceMock) CreateCalls() []struct {
	In1 *v3.HarborTag
} {
	var calls []struct {
		In1 *v3.HarborTag
	}
	lockHarborTagInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockHarborTagInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *HarborTagInterfaceMock) Delete(name string, options *v1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("HarborTagInterfaceMock.DeleteFunc: method is nil but HarborTagInterface.Delete was just called")
	}
	callInfo := struct {
		Name    string
		Options *v1.DeleteOptions
	}{
		Name:    name,
		Options: options,
	}
	lockHarborTagInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockHarborTagInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(name, options)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedHarborTagInterface.DeleteCalls())
func (mock *HarborTagInterfaceMock) DeleteCalls() []struct {
	Name    string
	Options *v1.DeleteOptions
} {
	var calls []struct {
		Name    string
		Options *v1.DeleteOptions
	}
	lockHarborTagInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockHarborTagInterfaceMockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *HarborTagInterfaceMock) DeleteCollection(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("HarborTagInterfaceMock.DeleteCollectionFunc: method is nil but HarborTagInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}{
		DeleteOpts: deleteOpts,
		ListOpts:   listOpts,
	}
	lockHarborTagInterfaceMockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	lockHarborTagInterfaceMockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(deleteOpts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedHarborTagInterface.DeleteCollectionCalls())
func (mock *HarborTagInterfaceMock) DeleteCollectionCalls() []struct {
	DeleteOpts *v1.DeleteOptions
	ListOpts   v1.ListOptions
} {
	var calls []struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}
	lockHarborTagInterfaceMockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	lockHarborTagInterfaceMockDeleteCollection.RUnlock()
	return calls
}

// DeleteNamespaced calls DeleteNamespacedFunc.
func (mock *HarborTagInterfaceMock) DeleteNamespaced(namespace string, name string, options *v1.DeleteOptions) error {
	if mock.DeleteNamespacedFunc == nil {
		panic("HarborTagInterfaceMock.DeleteNamespacedFunc: method is nil but HarborTagInterface.DeleteNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}{
		Namespace: namespace,
		Name:      name,
		Options:   options,
	}
	lockHarborTagInterfaceMockDeleteNamespaced.Lock()
	mock.calls.DeleteNamespaced = append(mock.calls.DeleteNamespaced, callInfo)
	lockHarborTagInterfaceMockDeleteNamespaced.Unlock()
	return mock.DeleteNamespacedFunc(namespace, name, options)
}

// DeleteNamespacedCalls gets all the calls that were made to DeleteNamespaced.
// Check the length with:
//     len(mockedHarborTagInterface.DeleteNamespacedCalls())
func (mock *HarborTagInterfaceMock) DeleteNamespacedCalls() []struct {
	Namespace string
	Name      string
	Options   *v1.DeleteOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}
	lockHarborTagInterfaceMockDeleteNamespaced.RLock()
	calls = mock.calls.DeleteNamespaced
	lockHarborTagInterfaceMockDeleteNamespaced.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *HarborTagInterfaceMock) Get(name string, opts v1.GetOptions) (*v3.HarborTag, error) {
	if mock.GetFunc == nil {
		panic("HarborTagInterfaceMock.GetFunc: method is nil but HarborTagInterface.Get was just called")
	}
	callInfo := struct {
		Name string
		Opts v1.GetOptions
	}{
		Name: name,
		Opts: opts,
	}
	lockHarborTagInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockHarborTagInterfaceMockGet.Unlock()
	return mock.GetFunc(name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedHarborTagInterface.GetCalls())
func (mock *HarborTagInterfaceMock) GetCalls() []struct {
	Name string
	Opts v1.GetOptions
} {
	var calls []struct {
		Name string
		Opts v1.GetOptions
	}
	lockHarborTagInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockHarborTagInterfaceMockGet.RUnlock()
	return calls
}

// GetNamespaced calls GetNamespacedFunc.
func (mock *HarborTagInterfaceMock) GetNamespaced(namespace string, name string, opts v1.GetOptions) (*v3.HarborTag, error) {
	if mock.GetNamespacedFunc == nil {
		panic("HarborTagInterfaceMock.GetNamespacedFunc: method is nil but HarborTagInterface.GetNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}{
		Namespace: namespace,
		Name:      name,
		Opts:      opts,
	}
	lockHarborTagInterfaceMockGetNamespaced.Lock()
	mock.calls.GetNamespaced = append(mock.calls.GetNamespaced, callInfo)
	lockHarborTagInterfaceMockGetNamespaced.Unlock()
	return mock.GetNamespacedFunc(namespace, name, opts)
}

// GetNamespacedCalls gets all the calls that were made to GetNamespaced.
// Check the length with:
//     len(mockedHarborTagInterface.GetNamespacedCalls())
func (mock *HarborTagInterfaceMock) GetNamespacedCalls() []struct {
	Namespace string
	Name      string
	Opts      v1.GetOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}
	lockHarborTagInterfaceMockGetNamespaced.RLock()
	calls = mock.calls.GetNamespaced
	lockHarborTagInterfaceMockGetNamespaced.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *HarborTagInterfaceMock) List(opts v1.ListOptions) (*v3.HarborTagList, error) {
	if mock.ListFunc == nil {
		panic("HarborTagInterfaceMock.ListFunc: method is nil but HarborTagInterface.List was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockHarborTagInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockHarborTagInterfaceMockList.Unlock()
	return mock.ListFunc(opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedHarborTagInterface.ListCalls())
func (mock *HarborTagInterfaceMock) ListCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockHarborTagInterfaceMockList.RLock()
	calls = mock.calls.List
	lockHarborTagInterfaceMockList.RUnlock()
	return calls
}

// ObjectClient calls ObjectClientFunc.
func (mock *HarborTagInterfaceMock) ObjectClient() *objectclient.ObjectClient {
	if mock.ObjectClientFunc == nil {
		panic("HarborTagInterfaceMock.ObjectClientFunc: method is nil but HarborTagInterface.ObjectClient was just called")
	}
	callInfo := struct {
	}{}
	lockHarborTagInterfaceMockObjectClient.Lock()
	mock.calls.ObjectClient = append(mock.calls.ObjectClient, callInfo)
	lockHarborTagInterfaceMockObjectClient.Unlock()
	return mock.ObjectClientFunc()
}

// ObjectClientCalls gets all the calls that were made to ObjectClient.
// Check the length with:
//     len(mockedHarborTagInterface.ObjectClientCalls())
func (mock *HarborTagInterfaceMock) ObjectClientCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborTagInterfaceMockObjectClient.RLock()
	calls = mock.calls.ObjectClient
	lockHarborTagInterfaceMockObjectClient.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *HarborTagInterfaceMock) Update(in1 *v3.HarborTag) (*v3.HarborTag, error) {
	if mock.UpdateFunc == nil {
		panic("HarborTagInterfaceMock.UpdateFunc: method is nil but HarborTagInterface.Update was just called")
	}
	callInfo := struct {
		In1 *v3.HarborTag
	}{
		In1: in1,
	}
	lockHarborTagInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockHarborTagInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(in1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedHarborTagInterface.UpdateCalls())
func (mock *HarborTagInterfaceMock) UpdateCalls() []struct {
	In1 *v3.HarborTag
} {
	var calls []struct {
		In1 *v3.HarborTag
	}
	lockHarborTagInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockHarborTagInterfaceMockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *HarborTagInterfaceMock) Watch(opts v1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("HarborTagInterfaceMock.WatchFunc: method is nil but HarborTagInterface.Watch was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockHarborTagInterfaceMockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	lockHarborTagInterfaceMockWatch.Unlock()
	return mock.WatchFunc(opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedHarborTagInterface.WatchCalls())
func (mock *HarborTagInterfaceMock) WatchCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockHarborTagInterfaceMockWatch.RLock()
	calls = mock.calls.Watch
	lockHarborTagInterfaceMockWatch.RUnlock()
	return calls
}

var (
	lockHarborTagsGetterMockHarborTags sync.RWMutex
)

// Ensure, that HarborTagsGetterMock does implement HarborTagsGetter.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborTagsGetter = &HarborTagsGetterMock{}

// HarborTagsGetterMock is a mock implementation of HarborTagsGetter.
//
//     func TestSomethingThatUsesHarborTagsGetter(t *testing.T) {
//
//         // make and configure a mocked HarborTagsGetter
//         mockedHarborTagsGetter := &HarborTagsGetterMock{
//             HarborTagsFunc: func(namespace string) v3.HarborTagInterface {
// 	               panic("mock out the HarborTags method")
//             },
//         }
//
//         // use mockedHarborTagsGetter in code that requires HarborTagsGetter
//         // and then make assertions.
//
//     }
type HarborTagsGetterMock struct {
	// HarborTagsFunc mocks the HarborTags method.
	HarborTagsFunc func(namespace string) v3.HarborTagInterface

	// calls tracks calls to the methods.
	calls struct {
		// HarborTags holds details about calls to the HarborTags method.
		HarborTags []struct {
			// Namespace is the namespace argument value.
			Namespace string
		}
	}
}

// HarborTags calls HarborTagsFunc.
func (mock *HarborTagsGetterMock) HarborTags(namespace string) v3.HarborTagInterface {
	if mock.HarborTagsFunc == nil {
		panic("HarborTagsGetterMock.HarborTagsFunc: method is nil but HarborTagsGetter.HarborTags was just called")
	}
	callInfo := struct {
		Namespace string
	}{
		Namespace: namespace,
	}
	lockHarborTagsGetterMockHarborTags.Lock()
	mock.calls.HarborTags = append(mock.calls.HarborTags, callInfo)
	lockHarborTagsGetterMockHarborTags.Unlock()
	return mock.HarborTagsFunc(namespace)
}

// HarborTagsCalls gets all the calls that were made to HarborTags.
// Check the length with:
//     len(mockedHarborTagsGetter.HarborTagsCalls())
func (mock *HarborTagsGetterMock) HarborTagsCalls() []struct {
	Namespace string
} {
	var calls []struct {
		Namespace string
	}
	lockHarborTagsGetterMockHarborTags.RLock()
	calls = mock.calls.HarborTags
	lockHarborTagsGetterMockHarborTags.RUnlock()
	return calls
}
