// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package fakes

import (
	context "context"
	sync "sync"

	controller "github.com/rancher/norman/controller"
	objectclient "github.com/rancher/norman/objectclient"
	v3 "github.com/rancher/types/apis/cluster.cattle.io/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

var (
	lockHarborProjectListerMockGet  sync.RWMutex
	lockHarborProjectListerMockList sync.RWMutex
)

// Ensure, that HarborProjectListerMock does implement HarborProjectLister.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborProjectLister = &HarborProjectListerMock{}

// HarborProjectListerMock is a mock implementation of HarborProjectLister.
//
//     func TestSomethingThatUsesHarborProjectLister(t *testing.T) {
//
//         // make and configure a mocked HarborProjectLister
//         mockedHarborProjectLister := &HarborProjectListerMock{
//             GetFunc: func(namespace string, name string) (*v3.HarborProject, error) {
// 	               panic("mock out the Get method")
//             },
//             ListFunc: func(namespace string, selector labels.Selector) ([]*v3.HarborProject, error) {
// 	               panic("mock out the List method")
//             },
//         }
//
//         // use mockedHarborProjectLister in code that requires HarborProjectLister
//         // and then make assertions.
//
//     }
type HarborProjectListerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(namespace string, name string) (*v3.HarborProject, error)

	// ListFunc mocks the List method.
	ListFunc func(namespace string, selector labels.Selector) ([]*v3.HarborProject, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Selector is the selector argument value.
			Selector labels.Selector
		}
	}
}

// Get calls GetFunc.
func (mock *HarborProjectListerMock) Get(namespace string, name string) (*v3.HarborProject, error) {
	if mock.GetFunc == nil {
		panic("HarborProjectListerMock.GetFunc: method is nil but HarborProjectLister.Get was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockHarborProjectListerMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockHarborProjectListerMockGet.Unlock()
	return mock.GetFunc(namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedHarborProjectLister.GetCalls())
func (mock *HarborProjectListerMock) GetCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockHarborProjectListerMockGet.RLock()
	calls = mock.calls.Get
	lockHarborProjectListerMockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *HarborProjectListerMock) List(namespace string, selector labels.Selector) ([]*v3.HarborProject, error) {
	if mock.ListFunc == nil {
		panic("HarborProjectListerMock.ListFunc: method is nil but HarborProjectLister.List was just called")
	}
	callInfo := struct {
		Namespace string
		Selector  labels.Selector
	}{
		Namespace: namespace,
		Selector:  selector,
	}
	lockHarborProjectListerMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockHarborProjectListerMockList.Unlock()
	return mock.ListFunc(namespace, selector)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedHarborProjectLister.ListCalls())
func (mock *HarborProjectListerMock) ListCalls() []struct {
	Namespace string
	Selector  labels.Selector
} {
	var calls []struct {
		Namespace string
		Selector  labels.Selector
	}
	lockHarborProjectListerMockList.RLock()
	calls = mock.calls.List
	lockHarborProjectListerMockList.RUnlock()
	return calls
}

var (
	lockHarborProjectControllerMockAddClusterScopedFeatureHandler sync.RWMutex
	lockHarborProjectControllerMockAddClusterScopedHandler        sync.RWMutex
	lockHarborProjectControllerMockAddFeatureHandler              sync.RWMutex
	lockHarborProjectControllerMockAddHandler                     sync.RWMutex
	lockHarborProjectControllerMockEnqueue                        sync.RWMutex
	lockHarborProjectControllerMockGeneric                        sync.RWMutex
	lockHarborProjectControllerMockInformer                       sync.RWMutex
	lockHarborProjectControllerMockLister                         sync.RWMutex
	lockHarborProjectControllerMockStart                          sync.RWMutex
	lockHarborProjectControllerMockSync                           sync.RWMutex
)

// Ensure, that HarborProjectControllerMock does implement HarborProjectController.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborProjectController = &HarborProjectControllerMock{}

// HarborProjectControllerMock is a mock implementation of HarborProjectController.
//
//     func TestSomethingThatUsesHarborProjectController(t *testing.T) {
//
//         // make and configure a mocked HarborProjectController
//         mockedHarborProjectController := &HarborProjectControllerMock{
//             AddClusterScopedFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedFeatureHandler method")
//             },
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, handler v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddFeatureHandler method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, handler v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             EnqueueFunc: func(namespace string, name string)  {
// 	               panic("mock out the Enqueue method")
//             },
//             GenericFunc: func() controller.GenericController {
// 	               panic("mock out the Generic method")
//             },
//             InformerFunc: func() cache.SharedIndexInformer {
// 	               panic("mock out the Informer method")
//             },
//             ListerFunc: func() v3.HarborProjectLister {
// 	               panic("mock out the Lister method")
//             },
//             StartFunc: func(ctx context.Context, threadiness int) error {
// 	               panic("mock out the Start method")
//             },
//             SyncFunc: func(ctx context.Context) error {
// 	               panic("mock out the Sync method")
//             },
//         }
//
//         // use mockedHarborProjectController in code that requires HarborProjectController
//         // and then make assertions.
//
//     }
type HarborProjectControllerMock struct {
	// AddClusterScopedFeatureHandlerFunc mocks the AddClusterScopedFeatureHandler method.
	AddClusterScopedFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborProjectHandlerFunc)

	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, handler v3.HarborProjectHandlerFunc)

	// AddFeatureHandlerFunc mocks the AddFeatureHandler method.
	AddFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, handler v3.HarborProjectHandlerFunc)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(namespace string, name string)

	// GenericFunc mocks the Generic method.
	GenericFunc func() controller.GenericController

	// InformerFunc mocks the Informer method.
	InformerFunc func() cache.SharedIndexInformer

	// ListerFunc mocks the Lister method.
	ListerFunc func() v3.HarborProjectLister

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, threadiness int) error

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedFeatureHandler holds details about calls to the AddClusterScopedFeatureHandler method.
		AddClusterScopedFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler v3.HarborProjectHandlerFunc
		}
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Handler is the handler argument value.
			Handler v3.HarborProjectHandlerFunc
		}
		// AddFeatureHandler holds details about calls to the AddFeatureHandler method.
		AddFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborProjectHandlerFunc
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Handler is the handler argument value.
			Handler v3.HarborProjectHandlerFunc
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Generic holds details about calls to the Generic method.
		Generic []struct {
		}
		// Informer holds details about calls to the Informer method.
		Informer []struct {
		}
		// Lister holds details about calls to the Lister method.
		Lister []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Threadiness is the threadiness argument value.
			Threadiness int
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// AddClusterScopedFeatureHandler calls AddClusterScopedFeatureHandlerFunc.
func (mock *HarborProjectControllerMock) AddClusterScopedFeatureHandler(ctx context.Context, enabled func() bool, name string, clusterName string, handler v3.HarborProjectHandlerFunc) {
	if mock.AddClusterScopedFeatureHandlerFunc == nil {
		panic("HarborProjectControllerMock.AddClusterScopedFeatureHandlerFunc: method is nil but HarborProjectController.AddClusterScopedFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Handler     v3.HarborProjectHandlerFunc
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockHarborProjectControllerMockAddClusterScopedFeatureHandler.Lock()
	mock.calls.AddClusterScopedFeatureHandler = append(mock.calls.AddClusterScopedFeatureHandler, callInfo)
	lockHarborProjectControllerMockAddClusterScopedFeatureHandler.Unlock()
	mock.AddClusterScopedFeatureHandlerFunc(ctx, enabled, name, clusterName, handler)
}

// AddClusterScopedFeatureHandlerCalls gets all the calls that were made to AddClusterScopedFeatureHandler.
// Check the length with:
//     len(mockedHarborProjectController.AddClusterScopedFeatureHandlerCalls())
func (mock *HarborProjectControllerMock) AddClusterScopedFeatureHandlerCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Handler     v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Handler     v3.HarborProjectHandlerFunc
	}
	lockHarborProjectControllerMockAddClusterScopedFeatureHandler.RLock()
	calls = mock.calls.AddClusterScopedFeatureHandler
	lockHarborProjectControllerMockAddClusterScopedFeatureHandler.RUnlock()
	return calls
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *HarborProjectControllerMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, handler v3.HarborProjectHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("HarborProjectControllerMock.AddClusterScopedHandlerFunc: method is nil but HarborProjectController.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v3.HarborProjectHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Handler:     handler,
	}
	lockHarborProjectControllerMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockHarborProjectControllerMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, handler)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedHarborProjectController.AddClusterScopedHandlerCalls())
func (mock *HarborProjectControllerMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Handler     v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Handler     v3.HarborProjectHandlerFunc
	}
	lockHarborProjectControllerMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockHarborProjectControllerMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddFeatureHandler calls AddFeatureHandlerFunc.
func (mock *HarborProjectControllerMock) AddFeatureHandler(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc) {
	if mock.AddFeatureHandlerFunc == nil {
		panic("HarborProjectControllerMock.AddFeatureHandlerFunc: method is nil but HarborProjectController.AddFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborProjectHandlerFunc
	}{
		Ctx:     ctx,
		Enabled: enabled,
		Name:    name,
		Sync:    sync,
	}
	lockHarborProjectControllerMockAddFeatureHandler.Lock()
	mock.calls.AddFeatureHandler = append(mock.calls.AddFeatureHandler, callInfo)
	lockHarborProjectControllerMockAddFeatureHandler.Unlock()
	mock.AddFeatureHandlerFunc(ctx, enabled, name, sync)
}

// AddFeatureHandlerCalls gets all the calls that were made to AddFeatureHandler.
// Check the length with:
//     len(mockedHarborProjectController.AddFeatureHandlerCalls())
func (mock *HarborProjectControllerMock) AddFeatureHandlerCalls() []struct {
	Ctx     context.Context
	Enabled func() bool
	Name    string
	Sync    v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborProjectHandlerFunc
	}
	lockHarborProjectControllerMockAddFeatureHandler.RLock()
	calls = mock.calls.AddFeatureHandler
	lockHarborProjectControllerMockAddFeatureHandler.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *HarborProjectControllerMock) AddHandler(ctx context.Context, name string, handler v3.HarborProjectHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("HarborProjectControllerMock.AddHandlerFunc: method is nil but HarborProjectController.AddHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Name    string
		Handler v3.HarborProjectHandlerFunc
	}{
		Ctx:     ctx,
		Name:    name,
		Handler: handler,
	}
	lockHarborProjectControllerMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockHarborProjectControllerMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, handler)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedHarborProjectController.AddHandlerCalls())
func (mock *HarborProjectControllerMock) AddHandlerCalls() []struct {
	Ctx     context.Context
	Name    string
	Handler v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Name    string
		Handler v3.HarborProjectHandlerFunc
	}
	lockHarborProjectControllerMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockHarborProjectControllerMockAddHandler.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *HarborProjectControllerMock) Enqueue(namespace string, name string) {
	if mock.EnqueueFunc == nil {
		panic("HarborProjectControllerMock.EnqueueFunc: method is nil but HarborProjectController.Enqueue was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
	}{
		Namespace: namespace,
		Name:      name,
	}
	lockHarborProjectControllerMockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	lockHarborProjectControllerMockEnqueue.Unlock()
	mock.EnqueueFunc(namespace, name)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//     len(mockedHarborProjectController.EnqueueCalls())
func (mock *HarborProjectControllerMock) EnqueueCalls() []struct {
	Namespace string
	Name      string
} {
	var calls []struct {
		Namespace string
		Name      string
	}
	lockHarborProjectControllerMockEnqueue.RLock()
	calls = mock.calls.Enqueue
	lockHarborProjectControllerMockEnqueue.RUnlock()
	return calls
}

// Generic calls GenericFunc.
func (mock *HarborProjectControllerMock) Generic() controller.GenericController {
	if mock.GenericFunc == nil {
		panic("HarborProjectControllerMock.GenericFunc: method is nil but HarborProjectController.Generic was just called")
	}
	callInfo := struct {
	}{}
	lockHarborProjectControllerMockGeneric.Lock()
	mock.calls.Generic = append(mock.calls.Generic, callInfo)
	lockHarborProjectControllerMockGeneric.Unlock()
	return mock.GenericFunc()
}

// GenericCalls gets all the calls that were made to Generic.
// Check the length with:
//     len(mockedHarborProjectController.GenericCalls())
func (mock *HarborProjectControllerMock) GenericCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborProjectControllerMockGeneric.RLock()
	calls = mock.calls.Generic
	lockHarborProjectControllerMockGeneric.RUnlock()
	return calls
}

// Informer calls InformerFunc.
func (mock *HarborProjectControllerMock) Informer() cache.SharedIndexInformer {
	if mock.InformerFunc == nil {
		panic("HarborProjectControllerMock.InformerFunc: method is nil but HarborProjectController.Informer was just called")
	}
	callInfo := struct {
	}{}
	lockHarborProjectControllerMockInformer.Lock()
	mock.calls.Informer = append(mock.calls.Informer, callInfo)
	lockHarborProjectControllerMockInformer.Unlock()
	return mock.InformerFunc()
}

// InformerCalls gets all the calls that were made to Informer.
// Check the length with:
//     len(mockedHarborProjectController.InformerCalls())
func (mock *HarborProjectControllerMock) InformerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborProjectControllerMockInformer.RLock()
	calls = mock.calls.Informer
	lockHarborProjectControllerMockInformer.RUnlock()
	return calls
}

// Lister calls ListerFunc.
func (mock *HarborProjectControllerMock) Lister() v3.HarborProjectLister {
	if mock.ListerFunc == nil {
		panic("HarborProjectControllerMock.ListerFunc: method is nil but HarborProjectController.Lister was just called")
	}
	callInfo := struct {
	}{}
	lockHarborProjectControllerMockLister.Lock()
	mock.calls.Lister = append(mock.calls.Lister, callInfo)
	lockHarborProjectControllerMockLister.Unlock()
	return mock.ListerFunc()
}

// ListerCalls gets all the calls that were made to Lister.
// Check the length with:
//     len(mockedHarborProjectController.ListerCalls())
func (mock *HarborProjectControllerMock) ListerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborProjectControllerMockLister.RLock()
	calls = mock.calls.Lister
	lockHarborProjectControllerMockLister.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *HarborProjectControllerMock) Start(ctx context.Context, threadiness int) error {
	if mock.StartFunc == nil {
		panic("HarborProjectControllerMock.StartFunc: method is nil but HarborProjectController.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Threadiness int
	}{
		Ctx:         ctx,
		Threadiness: threadiness,
	}
	lockHarborProjectControllerMockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	lockHarborProjectControllerMockStart.Unlock()
	return mock.StartFunc(ctx, threadiness)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedHarborProjectController.StartCalls())
func (mock *HarborProjectControllerMock) StartCalls() []struct {
	Ctx         context.Context
	Threadiness int
} {
	var calls []struct {
		Ctx         context.Context
		Threadiness int
	}
	lockHarborProjectControllerMockStart.RLock()
	calls = mock.calls.Start
	lockHarborProjectControllerMockStart.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *HarborProjectControllerMock) Sync(ctx context.Context) error {
	if mock.SyncFunc == nil {
		panic("HarborProjectControllerMock.SyncFunc: method is nil but HarborProjectController.Sync was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockHarborProjectControllerMockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	lockHarborProjectControllerMockSync.Unlock()
	return mock.SyncFunc(ctx)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//     len(mockedHarborProjectController.SyncCalls())
func (mock *HarborProjectControllerMock) SyncCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockHarborProjectControllerMockSync.RLock()
	calls = mock.calls.Sync
	lockHarborProjectControllerMockSync.RUnlock()
	return calls
}

var (
	lockHarborProjectInterfaceMockAddClusterScopedFeatureHandler   sync.RWMutex
	lockHarborProjectInterfaceMockAddClusterScopedFeatureLifecycle sync.RWMutex
	lockHarborProjectInterfaceMockAddClusterScopedHandler          sync.RWMutex
	lockHarborProjectInterfaceMockAddClusterScopedLifecycle        sync.RWMutex
	lockHarborProjectInterfaceMockAddFeatureHandler                sync.RWMutex
	lockHarborProjectInterfaceMockAddFeatureLifecycle              sync.RWMutex
	lockHarborProjectInterfaceMockAddHandler                       sync.RWMutex
	lockHarborProjectInterfaceMockAddLifecycle                     sync.RWMutex
	lockHarborProjectInterfaceMockController                       sync.RWMutex
	lockHarborProjectInterfaceMockCreate                           sync.RWMutex
	lockHarborProjectInterfaceMockDelete                           sync.RWMutex
	lockHarborProjectInterfaceMockDeleteCollection                 sync.RWMutex
	lockHarborProjectInterfaceMockDeleteNamespaced                 sync.RWMutex
	lockHarborProjectInterfaceMockGet                              sync.RWMutex
	lockHarborProjectInterfaceMockGetNamespaced                    sync.RWMutex
	lockHarborProjectInterfaceMockList                             sync.RWMutex
	lockHarborProjectInterfaceMockObjectClient                     sync.RWMutex
	lockHarborProjectInterfaceMockUpdate                           sync.RWMutex
	lockHarborProjectInterfaceMockWatch                            sync.RWMutex
)

// Ensure, that HarborProjectInterfaceMock does implement HarborProjectInterface.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborProjectInterface = &HarborProjectInterfaceMock{}

// HarborProjectInterfaceMock is a mock implementation of HarborProjectInterface.
//
//     func TestSomethingThatUsesHarborProjectInterface(t *testing.T) {
//
//         // make and configure a mocked HarborProjectInterface
//         mockedHarborProjectInterface := &HarborProjectInterfaceMock{
//             AddClusterScopedFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedFeatureHandler method")
//             },
//             AddClusterScopedFeatureLifecycleFunc: func(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborProjectLifecycle)  {
// 	               panic("mock out the AddClusterScopedFeatureLifecycle method")
//             },
//             AddClusterScopedHandlerFunc: func(ctx context.Context, name string, clusterName string, sync v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddClusterScopedHandler method")
//             },
//             AddClusterScopedLifecycleFunc: func(ctx context.Context, name string, clusterName string, lifecycle v3.HarborProjectLifecycle)  {
// 	               panic("mock out the AddClusterScopedLifecycle method")
//             },
//             AddFeatureHandlerFunc: func(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddFeatureHandler method")
//             },
//             AddFeatureLifecycleFunc: func(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborProjectLifecycle)  {
// 	               panic("mock out the AddFeatureLifecycle method")
//             },
//             AddHandlerFunc: func(ctx context.Context, name string, sync v3.HarborProjectHandlerFunc)  {
// 	               panic("mock out the AddHandler method")
//             },
//             AddLifecycleFunc: func(ctx context.Context, name string, lifecycle v3.HarborProjectLifecycle)  {
// 	               panic("mock out the AddLifecycle method")
//             },
//             ControllerFunc: func() v3.HarborProjectController {
// 	               panic("mock out the Controller method")
//             },
//             CreateFunc: func(in1 *v3.HarborProject) (*v3.HarborProject, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the Delete method")
//             },
//             DeleteCollectionFunc: func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
// 	               panic("mock out the DeleteCollection method")
//             },
//             DeleteNamespacedFunc: func(namespace string, name string, options *v1.DeleteOptions) error {
// 	               panic("mock out the DeleteNamespaced method")
//             },
//             GetFunc: func(name string, opts v1.GetOptions) (*v3.HarborProject, error) {
// 	               panic("mock out the Get method")
//             },
//             GetNamespacedFunc: func(namespace string, name string, opts v1.GetOptions) (*v3.HarborProject, error) {
// 	               panic("mock out the GetNamespaced method")
//             },
//             ListFunc: func(opts v1.ListOptions) (*v3.HarborProjectList, error) {
// 	               panic("mock out the List method")
//             },
//             ObjectClientFunc: func() *objectclient.ObjectClient {
// 	               panic("mock out the ObjectClient method")
//             },
//             UpdateFunc: func(in1 *v3.HarborProject) (*v3.HarborProject, error) {
// 	               panic("mock out the Update method")
//             },
//             WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
// 	               panic("mock out the Watch method")
//             },
//         }
//
//         // use mockedHarborProjectInterface in code that requires HarborProjectInterface
//         // and then make assertions.
//
//     }
type HarborProjectInterfaceMock struct {
	// AddClusterScopedFeatureHandlerFunc mocks the AddClusterScopedFeatureHandler method.
	AddClusterScopedFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborProjectHandlerFunc)

	// AddClusterScopedFeatureLifecycleFunc mocks the AddClusterScopedFeatureLifecycle method.
	AddClusterScopedFeatureLifecycleFunc func(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborProjectLifecycle)

	// AddClusterScopedHandlerFunc mocks the AddClusterScopedHandler method.
	AddClusterScopedHandlerFunc func(ctx context.Context, name string, clusterName string, sync v3.HarborProjectHandlerFunc)

	// AddClusterScopedLifecycleFunc mocks the AddClusterScopedLifecycle method.
	AddClusterScopedLifecycleFunc func(ctx context.Context, name string, clusterName string, lifecycle v3.HarborProjectLifecycle)

	// AddFeatureHandlerFunc mocks the AddFeatureHandler method.
	AddFeatureHandlerFunc func(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc)

	// AddFeatureLifecycleFunc mocks the AddFeatureLifecycle method.
	AddFeatureLifecycleFunc func(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborProjectLifecycle)

	// AddHandlerFunc mocks the AddHandler method.
	AddHandlerFunc func(ctx context.Context, name string, sync v3.HarborProjectHandlerFunc)

	// AddLifecycleFunc mocks the AddLifecycle method.
	AddLifecycleFunc func(ctx context.Context, name string, lifecycle v3.HarborProjectLifecycle)

	// ControllerFunc mocks the Controller method.
	ControllerFunc func() v3.HarborProjectController

	// CreateFunc mocks the Create method.
	CreateFunc func(in1 *v3.HarborProject) (*v3.HarborProject, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(name string, options *v1.DeleteOptions) error

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error

	// DeleteNamespacedFunc mocks the DeleteNamespaced method.
	DeleteNamespacedFunc func(namespace string, name string, options *v1.DeleteOptions) error

	// GetFunc mocks the Get method.
	GetFunc func(name string, opts v1.GetOptions) (*v3.HarborProject, error)

	// GetNamespacedFunc mocks the GetNamespaced method.
	GetNamespacedFunc func(namespace string, name string, opts v1.GetOptions) (*v3.HarborProject, error)

	// ListFunc mocks the List method.
	ListFunc func(opts v1.ListOptions) (*v3.HarborProjectList, error)

	// ObjectClientFunc mocks the ObjectClient method.
	ObjectClientFunc func() *objectclient.ObjectClient

	// UpdateFunc mocks the Update method.
	UpdateFunc func(in1 *v3.HarborProject) (*v3.HarborProject, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(opts v1.ListOptions) (watch.Interface, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddClusterScopedFeatureHandler holds details about calls to the AddClusterScopedFeatureHandler method.
		AddClusterScopedFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync v3.HarborProjectHandlerFunc
		}
		// AddClusterScopedFeatureLifecycle holds details about calls to the AddClusterScopedFeatureLifecycle method.
		AddClusterScopedFeatureLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborProjectLifecycle
		}
		// AddClusterScopedHandler holds details about calls to the AddClusterScopedHandler method.
		AddClusterScopedHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Sync is the sync argument value.
			Sync v3.HarborProjectHandlerFunc
		}
		// AddClusterScopedLifecycle holds details about calls to the AddClusterScopedLifecycle method.
		AddClusterScopedLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// ClusterName is the clusterName argument value.
			ClusterName string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborProjectLifecycle
		}
		// AddFeatureHandler holds details about calls to the AddFeatureHandler method.
		AddFeatureHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborProjectHandlerFunc
		}
		// AddFeatureLifecycle holds details about calls to the AddFeatureLifecycle method.
		AddFeatureLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Enabled is the enabled argument value.
			Enabled func() bool
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborProjectLifecycle
		}
		// AddHandler holds details about calls to the AddHandler method.
		AddHandler []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Sync is the sync argument value.
			Sync v3.HarborProjectHandlerFunc
		}
		// AddLifecycle holds details about calls to the AddLifecycle method.
		AddLifecycle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Lifecycle is the lifecycle argument value.
			Lifecycle v3.HarborProjectLifecycle
		}
		// Controller holds details about calls to the Controller method.
		Controller []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// In1 is the in1 argument value.
			In1 *v3.HarborProject
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// DeleteOpts is the deleteOpts argument value.
			DeleteOpts *v1.DeleteOptions
			// ListOpts is the listOpts argument value.
			ListOpts v1.ListOptions
		}
		// DeleteNamespaced holds details about calls to the DeleteNamespaced method.
		DeleteNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Options is the options argument value.
			Options *v1.DeleteOptions
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// GetNamespaced holds details about calls to the GetNamespaced method.
		GetNamespaced []struct {
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts v1.GetOptions
		}
		// List holds details about calls to the List method.
		List []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
		// ObjectClient holds details about calls to the ObjectClient method.
		ObjectClient []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// In1 is the in1 argument value.
			In1 *v3.HarborProject
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Opts is the opts argument value.
			Opts v1.ListOptions
		}
	}
}

// AddClusterScopedFeatureHandler calls AddClusterScopedFeatureHandlerFunc.
func (mock *HarborProjectInterfaceMock) AddClusterScopedFeatureHandler(ctx context.Context, enabled func() bool, name string, clusterName string, sync v3.HarborProjectHandlerFunc) {
	if mock.AddClusterScopedFeatureHandlerFunc == nil {
		panic("HarborProjectInterfaceMock.AddClusterScopedFeatureHandlerFunc: method is nil but HarborProjectInterface.AddClusterScopedFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Sync        v3.HarborProjectHandlerFunc
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockHarborProjectInterfaceMockAddClusterScopedFeatureHandler.Lock()
	mock.calls.AddClusterScopedFeatureHandler = append(mock.calls.AddClusterScopedFeatureHandler, callInfo)
	lockHarborProjectInterfaceMockAddClusterScopedFeatureHandler.Unlock()
	mock.AddClusterScopedFeatureHandlerFunc(ctx, enabled, name, clusterName, sync)
}

// AddClusterScopedFeatureHandlerCalls gets all the calls that were made to AddClusterScopedFeatureHandler.
// Check the length with:
//     len(mockedHarborProjectInterface.AddClusterScopedFeatureHandlerCalls())
func (mock *HarborProjectInterfaceMock) AddClusterScopedFeatureHandlerCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Sync        v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Sync        v3.HarborProjectHandlerFunc
	}
	lockHarborProjectInterfaceMockAddClusterScopedFeatureHandler.RLock()
	calls = mock.calls.AddClusterScopedFeatureHandler
	lockHarborProjectInterfaceMockAddClusterScopedFeatureHandler.RUnlock()
	return calls
}

// AddClusterScopedFeatureLifecycle calls AddClusterScopedFeatureLifecycleFunc.
func (mock *HarborProjectInterfaceMock) AddClusterScopedFeatureLifecycle(ctx context.Context, enabled func() bool, name string, clusterName string, lifecycle v3.HarborProjectLifecycle) {
	if mock.AddClusterScopedFeatureLifecycleFunc == nil {
		panic("HarborProjectInterfaceMock.AddClusterScopedFeatureLifecycleFunc: method is nil but HarborProjectInterface.AddClusterScopedFeatureLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Lifecycle   v3.HarborProjectLifecycle
	}{
		Ctx:         ctx,
		Enabled:     enabled,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockHarborProjectInterfaceMockAddClusterScopedFeatureLifecycle.Lock()
	mock.calls.AddClusterScopedFeatureLifecycle = append(mock.calls.AddClusterScopedFeatureLifecycle, callInfo)
	lockHarborProjectInterfaceMockAddClusterScopedFeatureLifecycle.Unlock()
	mock.AddClusterScopedFeatureLifecycleFunc(ctx, enabled, name, clusterName, lifecycle)
}

// AddClusterScopedFeatureLifecycleCalls gets all the calls that were made to AddClusterScopedFeatureLifecycle.
// Check the length with:
//     len(mockedHarborProjectInterface.AddClusterScopedFeatureLifecycleCalls())
func (mock *HarborProjectInterfaceMock) AddClusterScopedFeatureLifecycleCalls() []struct {
	Ctx         context.Context
	Enabled     func() bool
	Name        string
	ClusterName string
	Lifecycle   v3.HarborProjectLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Enabled     func() bool
		Name        string
		ClusterName string
		Lifecycle   v3.HarborProjectLifecycle
	}
	lockHarborProjectInterfaceMockAddClusterScopedFeatureLifecycle.RLock()
	calls = mock.calls.AddClusterScopedFeatureLifecycle
	lockHarborProjectInterfaceMockAddClusterScopedFeatureLifecycle.RUnlock()
	return calls
}

// AddClusterScopedHandler calls AddClusterScopedHandlerFunc.
func (mock *HarborProjectInterfaceMock) AddClusterScopedHandler(ctx context.Context, name string, clusterName string, sync v3.HarborProjectHandlerFunc) {
	if mock.AddClusterScopedHandlerFunc == nil {
		panic("HarborProjectInterfaceMock.AddClusterScopedHandlerFunc: method is nil but HarborProjectInterface.AddClusterScopedHandler was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v3.HarborProjectHandlerFunc
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Sync:        sync,
	}
	lockHarborProjectInterfaceMockAddClusterScopedHandler.Lock()
	mock.calls.AddClusterScopedHandler = append(mock.calls.AddClusterScopedHandler, callInfo)
	lockHarborProjectInterfaceMockAddClusterScopedHandler.Unlock()
	mock.AddClusterScopedHandlerFunc(ctx, name, clusterName, sync)
}

// AddClusterScopedHandlerCalls gets all the calls that were made to AddClusterScopedHandler.
// Check the length with:
//     len(mockedHarborProjectInterface.AddClusterScopedHandlerCalls())
func (mock *HarborProjectInterfaceMock) AddClusterScopedHandlerCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Sync        v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Sync        v3.HarborProjectHandlerFunc
	}
	lockHarborProjectInterfaceMockAddClusterScopedHandler.RLock()
	calls = mock.calls.AddClusterScopedHandler
	lockHarborProjectInterfaceMockAddClusterScopedHandler.RUnlock()
	return calls
}

// AddClusterScopedLifecycle calls AddClusterScopedLifecycleFunc.
func (mock *HarborProjectInterfaceMock) AddClusterScopedLifecycle(ctx context.Context, name string, clusterName string, lifecycle v3.HarborProjectLifecycle) {
	if mock.AddClusterScopedLifecycleFunc == nil {
		panic("HarborProjectInterfaceMock.AddClusterScopedLifecycleFunc: method is nil but HarborProjectInterface.AddClusterScopedLifecycle was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v3.HarborProjectLifecycle
	}{
		Ctx:         ctx,
		Name:        name,
		ClusterName: clusterName,
		Lifecycle:   lifecycle,
	}
	lockHarborProjectInterfaceMockAddClusterScopedLifecycle.Lock()
	mock.calls.AddClusterScopedLifecycle = append(mock.calls.AddClusterScopedLifecycle, callInfo)
	lockHarborProjectInterfaceMockAddClusterScopedLifecycle.Unlock()
	mock.AddClusterScopedLifecycleFunc(ctx, name, clusterName, lifecycle)
}

// AddClusterScopedLifecycleCalls gets all the calls that were made to AddClusterScopedLifecycle.
// Check the length with:
//     len(mockedHarborProjectInterface.AddClusterScopedLifecycleCalls())
func (mock *HarborProjectInterfaceMock) AddClusterScopedLifecycleCalls() []struct {
	Ctx         context.Context
	Name        string
	ClusterName string
	Lifecycle   v3.HarborProjectLifecycle
} {
	var calls []struct {
		Ctx         context.Context
		Name        string
		ClusterName string
		Lifecycle   v3.HarborProjectLifecycle
	}
	lockHarborProjectInterfaceMockAddClusterScopedLifecycle.RLock()
	calls = mock.calls.AddClusterScopedLifecycle
	lockHarborProjectInterfaceMockAddClusterScopedLifecycle.RUnlock()
	return calls
}

// AddFeatureHandler calls AddFeatureHandlerFunc.
func (mock *HarborProjectInterfaceMock) AddFeatureHandler(ctx context.Context, enabled func() bool, name string, sync v3.HarborProjectHandlerFunc) {
	if mock.AddFeatureHandlerFunc == nil {
		panic("HarborProjectInterfaceMock.AddFeatureHandlerFunc: method is nil but HarborProjectInterface.AddFeatureHandler was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborProjectHandlerFunc
	}{
		Ctx:     ctx,
		Enabled: enabled,
		Name:    name,
		Sync:    sync,
	}
	lockHarborProjectInterfaceMockAddFeatureHandler.Lock()
	mock.calls.AddFeatureHandler = append(mock.calls.AddFeatureHandler, callInfo)
	lockHarborProjectInterfaceMockAddFeatureHandler.Unlock()
	mock.AddFeatureHandlerFunc(ctx, enabled, name, sync)
}

// AddFeatureHandlerCalls gets all the calls that were made to AddFeatureHandler.
// Check the length with:
//     len(mockedHarborProjectInterface.AddFeatureHandlerCalls())
func (mock *HarborProjectInterfaceMock) AddFeatureHandlerCalls() []struct {
	Ctx     context.Context
	Enabled func() bool
	Name    string
	Sync    v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx     context.Context
		Enabled func() bool
		Name    string
		Sync    v3.HarborProjectHandlerFunc
	}
	lockHarborProjectInterfaceMockAddFeatureHandler.RLock()
	calls = mock.calls.AddFeatureHandler
	lockHarborProjectInterfaceMockAddFeatureHandler.RUnlock()
	return calls
}

// AddFeatureLifecycle calls AddFeatureLifecycleFunc.
func (mock *HarborProjectInterfaceMock) AddFeatureLifecycle(ctx context.Context, enabled func() bool, name string, lifecycle v3.HarborProjectLifecycle) {
	if mock.AddFeatureLifecycleFunc == nil {
		panic("HarborProjectInterfaceMock.AddFeatureLifecycleFunc: method is nil but HarborProjectInterface.AddFeatureLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Enabled   func() bool
		Name      string
		Lifecycle v3.HarborProjectLifecycle
	}{
		Ctx:       ctx,
		Enabled:   enabled,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockHarborProjectInterfaceMockAddFeatureLifecycle.Lock()
	mock.calls.AddFeatureLifecycle = append(mock.calls.AddFeatureLifecycle, callInfo)
	lockHarborProjectInterfaceMockAddFeatureLifecycle.Unlock()
	mock.AddFeatureLifecycleFunc(ctx, enabled, name, lifecycle)
}

// AddFeatureLifecycleCalls gets all the calls that were made to AddFeatureLifecycle.
// Check the length with:
//     len(mockedHarborProjectInterface.AddFeatureLifecycleCalls())
func (mock *HarborProjectInterfaceMock) AddFeatureLifecycleCalls() []struct {
	Ctx       context.Context
	Enabled   func() bool
	Name      string
	Lifecycle v3.HarborProjectLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Enabled   func() bool
		Name      string
		Lifecycle v3.HarborProjectLifecycle
	}
	lockHarborProjectInterfaceMockAddFeatureLifecycle.RLock()
	calls = mock.calls.AddFeatureLifecycle
	lockHarborProjectInterfaceMockAddFeatureLifecycle.RUnlock()
	return calls
}

// AddHandler calls AddHandlerFunc.
func (mock *HarborProjectInterfaceMock) AddHandler(ctx context.Context, name string, sync v3.HarborProjectHandlerFunc) {
	if mock.AddHandlerFunc == nil {
		panic("HarborProjectInterfaceMock.AddHandlerFunc: method is nil but HarborProjectInterface.AddHandler was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Sync v3.HarborProjectHandlerFunc
	}{
		Ctx:  ctx,
		Name: name,
		Sync: sync,
	}
	lockHarborProjectInterfaceMockAddHandler.Lock()
	mock.calls.AddHandler = append(mock.calls.AddHandler, callInfo)
	lockHarborProjectInterfaceMockAddHandler.Unlock()
	mock.AddHandlerFunc(ctx, name, sync)
}

// AddHandlerCalls gets all the calls that were made to AddHandler.
// Check the length with:
//     len(mockedHarborProjectInterface.AddHandlerCalls())
func (mock *HarborProjectInterfaceMock) AddHandlerCalls() []struct {
	Ctx  context.Context
	Name string
	Sync v3.HarborProjectHandlerFunc
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Sync v3.HarborProjectHandlerFunc
	}
	lockHarborProjectInterfaceMockAddHandler.RLock()
	calls = mock.calls.AddHandler
	lockHarborProjectInterfaceMockAddHandler.RUnlock()
	return calls
}

// AddLifecycle calls AddLifecycleFunc.
func (mock *HarborProjectInterfaceMock) AddLifecycle(ctx context.Context, name string, lifecycle v3.HarborProjectLifecycle) {
	if mock.AddLifecycleFunc == nil {
		panic("HarborProjectInterfaceMock.AddLifecycleFunc: method is nil but HarborProjectInterface.AddLifecycle was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Name      string
		Lifecycle v3.HarborProjectLifecycle
	}{
		Ctx:       ctx,
		Name:      name,
		Lifecycle: lifecycle,
	}
	lockHarborProjectInterfaceMockAddLifecycle.Lock()
	mock.calls.AddLifecycle = append(mock.calls.AddLifecycle, callInfo)
	lockHarborProjectInterfaceMockAddLifecycle.Unlock()
	mock.AddLifecycleFunc(ctx, name, lifecycle)
}

// AddLifecycleCalls gets all the calls that were made to AddLifecycle.
// Check the length with:
//     len(mockedHarborProjectInterface.AddLifecycleCalls())
func (mock *HarborProjectInterfaceMock) AddLifecycleCalls() []struct {
	Ctx       context.Context
	Name      string
	Lifecycle v3.HarborProjectLifecycle
} {
	var calls []struct {
		Ctx       context.Context
		Name      string
		Lifecycle v3.HarborProjectLifecycle
	}
	lockHarborProjectInterfaceMockAddLifecycle.RLock()
	calls = mock.calls.AddLifecycle
	lockHarborProjectInterfaceMockAddLifecycle.RUnlock()
	return calls
}

// Controller calls ControllerFunc.
func (mock *HarborProjectInterfaceMock) Controller() v3.HarborProjectController {
	if mock.ControllerFunc == nil {
		panic("HarborProjectInterfaceMock.ControllerFunc: method is nil but HarborProjectInterface.Controller was just called")
	}
	callInfo := struct {
	}{}
	lockHarborProjectInterfaceMockController.Lock()
	mock.calls.Controller = append(mock.calls.Controller, callInfo)
	lockHarborProjectInterfaceMockController.Unlock()
	return mock.ControllerFunc()
}

// ControllerCalls gets all the calls that were made to Controller.
// Check the length with:
//     len(mockedHarborProjectInterface.ControllerCalls())
func (mock *HarborProjectInterfaceMock) ControllerCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborProjectInterfaceMockController.RLock()
	calls = mock.calls.Controller
	lockHarborProjectInterfaceMockController.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *HarborProjectInterfaceMock) Create(in1 *v3.HarborProject) (*v3.HarborProject, error) {
	if mock.CreateFunc == nil {
		panic("HarborProjectInterfaceMock.CreateFunc: method is nil but HarborProjectInterface.Create was just called")
	}
	callInfo := struct {
		In1 *v3.HarborProject
	}{
		In1: in1,
	}
	lockHarborProjectInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockHarborProjectInterfaceMockCreate.Unlock()
	return mock.CreateFunc(in1)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedHarborProjectInterface.CreateCalls())
func (mock *HarborProjectInterfaceMock) CreateCalls() []struct {
	In1 *v3.HarborProject
} {
	var calls []struct {
		In1 *v3.HarborProject
	}
	lockHarborProjectInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockHarborProjectInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *HarborProjectInterfaceMock) Delete(name string, options *v1.DeleteOptions) error {
	if mock.DeleteFunc == nil {
		panic("HarborProjectInterfaceMock.DeleteFunc: method is nil but HarborProjectInterface.Delete was just called")
	}
	callInfo := struct {
		Name    string
		Options *v1.DeleteOptions
	}{
		Name:    name,
		Options: options,
	}
	lockHarborProjectInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockHarborProjectInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(name, options)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedHarborProjectInterface.DeleteCalls())
func (mock *HarborProjectInterfaceMock) DeleteCalls() []struct {
	Name    string
	Options *v1.DeleteOptions
} {
	var calls []struct {
		Name    string
		Options *v1.DeleteOptions
	}
	lockHarborProjectInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockHarborProjectInterfaceMockDelete.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *HarborProjectInterfaceMock) DeleteCollection(deleteOpts *v1.DeleteOptions, listOpts v1.ListOptions) error {
	if mock.DeleteCollectionFunc == nil {
		panic("HarborProjectInterfaceMock.DeleteCollectionFunc: method is nil but HarborProjectInterface.DeleteCollection was just called")
	}
	callInfo := struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}{
		DeleteOpts: deleteOpts,
		ListOpts:   listOpts,
	}
	lockHarborProjectInterfaceMockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	lockHarborProjectInterfaceMockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(deleteOpts, listOpts)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//     len(mockedHarborProjectInterface.DeleteCollectionCalls())
func (mock *HarborProjectInterfaceMock) DeleteCollectionCalls() []struct {
	DeleteOpts *v1.DeleteOptions
	ListOpts   v1.ListOptions
} {
	var calls []struct {
		DeleteOpts *v1.DeleteOptions
		ListOpts   v1.ListOptions
	}
	lockHarborProjectInterfaceMockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	lockHarborProjectInterfaceMockDeleteCollection.RUnlock()
	return calls
}

// DeleteNamespaced calls DeleteNamespacedFunc.
func (mock *HarborProjectInterfaceMock) DeleteNamespaced(namespace string, name string, options *v1.DeleteOptions) error {
	if mock.DeleteNamespacedFunc == nil {
		panic("HarborProjectInterfaceMock.DeleteNamespacedFunc: method is nil but HarborProjectInterface.DeleteNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}{
		Namespace: namespace,
		Name:      name,
		Options:   options,
	}
	lockHarborProjectInterfaceMockDeleteNamespaced.Lock()
	mock.calls.DeleteNamespaced = append(mock.calls.DeleteNamespaced, callInfo)
	lockHarborProjectInterfaceMockDeleteNamespaced.Unlock()
	return mock.DeleteNamespacedFunc(namespace, name, options)
}

// DeleteNamespacedCalls gets all the calls that were made to DeleteNamespaced.
// Check the length with:
//     len(mockedHarborProjectInterface.DeleteNamespacedCalls())
func (mock *HarborProjectInterfaceMock) DeleteNamespacedCalls() []struct {
	Namespace string
	Name      string
	Options   *v1.DeleteOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Options   *v1.DeleteOptions
	}
	lockHarborProjectInterfaceMockDeleteNamespaced.RLock()
	calls = mock.calls.DeleteNamespaced
	lockHarborProjectInterfaceMockDeleteNamespaced.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *HarborProjectInterfaceMock) Get(name string, opts v1.GetOptions) (*v3.HarborProject, error) {
	if mock.GetFunc == nil {
		panic("HarborProjectInterfaceMock.GetFunc: method is nil but HarborProjectInterface.Get was just called")
	}
	callInfo := struct {
		Name string
		Opts v1.GetOptions
	}{
		Name: name,
		Opts: opts,
	}
	lockHarborProjectInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockHarborProjectInterfaceMockGet.Unlock()
	return mock.GetFunc(name, opts)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedHarborProjectInterface.GetCalls())
func (mock *HarborProjectInterfaceMock) GetCalls() []struct {
	Name string
	Opts v1.GetOptions
} {
	var calls []struct {
		Name string
		Opts v1.GetOptions
	}
	lockHarborProjectInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockHarborProjectInterfaceMockGet.RUnlock()
	return calls
}

// GetNamespaced calls GetNamespacedFunc.
func (mock *HarborProjectInterfaceMock) GetNamespaced(namespace string, name string, opts v1.GetOptions) (*v3.HarborProject, error) {
	if mock.GetNamespacedFunc == nil {
		panic("HarborProjectInterfaceMock.GetNamespacedFunc: method is nil but HarborProjectInterface.GetNamespaced was just called")
	}
	callInfo := struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}{
		Namespace: namespace,
		Name:      name,
		Opts:      opts,
	}
	lockHarborProjectInterfaceMockGetNamespaced.Lock()
	mock.calls.GetNamespaced = append(mock.calls.GetNamespaced, callInfo)
	lockHarborProjectInterfaceMockGetNamespaced.Unlock()
	return mock.GetNamespacedFunc(namespace, name, opts)
}

// GetNamespacedCalls gets all the calls that were made to GetNamespaced.
// Check the length with:
//     len(mockedHarborProjectInterface.GetNamespacedCalls())
func (mock *HarborProjectInterfaceMock) GetNamespacedCalls() []struct {
	Namespace string
	Name      string
	Opts      v1.GetOptions
} {
	var calls []struct {
		Namespace string
		Name      string
		Opts      v1.GetOptions
	}
	lockHarborProjectInterfaceMockGetNamespaced.RLock()
	calls = mock.calls.GetNamespaced
	lockHarborProjectInterfaceMockGetNamespaced.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *HarborProjectInterfaceMock) List(opts v1.ListOptions) (*v3.HarborProjectList, error) {
	if mock.ListFunc == nil {
		panic("HarborProjectInterfaceMock.ListFunc: method is nil but HarborProjectInterface.List was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockHarborProjectInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockHarborProjectInterfaceMockList.Unlock()
	return mock.ListFunc(opts)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedHarborProjectInterface.ListCalls())
func (mock *HarborProjectInterfaceMock) ListCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockHarborProjectInterfaceMockList.RLock()
	calls = mock.calls.List
	lockHarborProjectInterfaceMockList.RUnlock()
	return calls
}

// ObjectClient calls ObjectClientFunc.
func (mock *HarborProjectInterfaceMock) ObjectClient() *objectclient.ObjectClient {
	if mock.ObjectClientFunc == nil {
		panic("HarborProjectInterfaceMock.ObjectClientFunc: method is nil but HarborProjectInterface.ObjectClient was just called")
	}
	callInfo := struct {
	}{}
	lockHarborProjectInterfaceMockObjectClient.Lock()
	mock.calls.ObjectClient = append(mock.calls.ObjectClient, callInfo)
	lockHarborProjectInterfaceMockObjectClient.Unlock()
	return mock.ObjectClientFunc()
}

// ObjectClientCalls gets all the calls that were made to ObjectClient.
// Check the length with:
//     len(mockedHarborProjectInterface.ObjectClientCalls())
func (mock *HarborProjectInterfaceMock) ObjectClientCalls() []struct {
} {
	var calls []struct {
	}
	lockHarborProjectInterfaceMockObjectClient.RLock()
	calls = mock.calls.ObjectClient
	lockHarborProjectInterfaceMockObjectClient.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *HarborProjectInterfaceMock) Update(in1 *v3.HarborProject) (*v3.HarborProject, error) {
	if mock.UpdateFunc == nil {
		panic("HarborProjectInterfaceMock.UpdateFunc: method is nil but HarborProjectInterface.Update was just called")
	}
	callInfo := struct {
		In1 *v3.HarborProject
	}{
		In1: in1,
	}
	lockHarborProjectInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockHarborProjectInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(in1)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedHarborProjectInterface.UpdateCalls())
func (mock *HarborProjectInterfaceMock) UpdateCalls() []struct {
	In1 *v3.HarborProject
} {
	var calls []struct {
		In1 *v3.HarborProject
	}
	lockHarborProjectInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockHarborProjectInterfaceMockUpdate.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *HarborProjectInterfaceMock) Watch(opts v1.ListOptions) (watch.Interface, error) {
	if mock.WatchFunc == nil {
		panic("HarborProjectInterfaceMock.WatchFunc: method is nil but HarborProjectInterface.Watch was just called")
	}
	callInfo := struct {
		Opts v1.ListOptions
	}{
		Opts: opts,
	}
	lockHarborProjectInterfaceMockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	lockHarborProjectInterfaceMockWatch.Unlock()
	return mock.WatchFunc(opts)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//     len(mockedHarborProjectInterface.WatchCalls())
func (mock *HarborProjectInterfaceMock) WatchCalls() []struct {
	Opts v1.ListOptions
} {
	var calls []struct {
		Opts v1.ListOptions
	}
	lockHarborProjectInterfaceMockWatch.RLock()
	calls = mock.calls.Watch
	lockHarborProjectInterfaceMockWatch.RUnlock()
	return calls
}

var (
	lockHarborProjectsGetterMockHarborProjects sync.RWMutex
)

// Ensure, that HarborProjectsGetterMock does implement HarborProjectsGetter.
// If this is not the case, regenerate this file with moq.
var _ v3.HarborProjectsGetter = &HarborProjectsGetterMock{}

// HarborProjectsGetterMock is a mock implementation of HarborProjectsGetter.
//
//     func TestSomethingThatUsesHarborProjectsGetter(t *testing.T) {
//
//         // make and configure a mocked HarborProjectsGetter
//         mockedHarborProjectsGetter := &HarborProjectsGetterMock{
//             HarborProjectsFunc: func(namespace string) v3.HarborProjectInterface {
// 	               panic("mock out the HarborProjects method")
//             },
//         }
//
//         // use mockedHarborProjectsGetter in code that requires HarborProjectsGetter
//         // and then make assertions.
//
//     }
type HarborProjectsGetterMock struct {
	// HarborProjectsFunc mocks the HarborProjects method.
	HarborProjectsFunc func(namespace string) v3.HarborProjectInterface

	// calls tracks calls to the methods.
	calls struct {
		// HarborProjects holds details about calls to the HarborProjects method.
		HarborProjects []struct {
			// Namespace is the namespace argument value.
			Namespace string
		}
	}
}

// HarborProjects calls HarborProjectsFunc.
func (mock *HarborProjectsGetterMock) HarborProjects(namespace string) v3.HarborProjectInterface {
	if mock.HarborProjectsFunc == nil {
		panic("HarborProjectsGetterMock.HarborProjectsFunc: method is nil but HarborProjectsGetter.HarborProjects was just called")
	}
	callInfo := struct {
		Namespace string
	}{
		Namespace: namespace,
	}
	lockHarborProjectsGetterMockHarborProjects.Lock()
	mock.calls.HarborProjects = append(mock.calls.HarborProjects, callInfo)
	lockHarborProjectsGetterMockHarborProjects.Unlock()
	return mock.HarborProjectsFunc(namespace)
}

// HarborProjectsCalls gets all the calls that were made to HarborProjects.
// Check the length with:
//     len(mockedHarborProjectsGetter.HarborProjectsCalls())
func (mock *HarborProjectsGetterMock) HarborProjectsCalls() []struct {
	Namespace string
} {
	var calls []struct {
		Namespace string
	}
	lockHarborProjectsGetterMockHarborProjects.RLock()
	calls = mock.calls.HarborProjects
	lockHarborProjectsGetterMockHarborProjects.RUnlock()
	return calls
}
